FROM python:3

# set a directory for the app
WORKDIR A:/Python/Simple_RESTful_Flask_application/

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# define the port number the container should expose
EXPOSE 4567

# run the command
CMD ["python", "./flask_app"]